[package]
name = "aws-sdk-sys"
version = "0.1.0"
edition = "2021"
link = "aws-sdk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.48"
anyhow = "1.0.65"

[dependencies]
curl-sys = { path = "../curl-sys" }
